export const START_GAME = 'START_GAME';
export const RESTART_GAME = 'RESTART_GAME';

export const INIT_SHIPS = 'INIT_SHIPS';
export const SELECT_SHIP = 'SELECT_SHIP';
export const ROTATE_SHIP = 'ROTATE_SHIP';
export const SET_SHIP_POSITION = 'SET_SHIP_POSITION';

export const HIGHLIGHT_POSSIBLE_SELECTION = 'HIGHLIGHT_POSSIBLE_SELECTION';
